# Generated by Django 2.0.6 on 2018-07-27 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host_management', '0017_auto_20180724_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='平台名称')),
                ('deploy_time', models.DateField(verbose_name='上线时间')),
                ('request_user', models.CharField(max_length=20, verbose_name='发起人')),
                ('deploy_result', models.PositiveSmallIntegerField(choices=[(1, '成功'), (2, '失败')], default=1, verbose_name='上线结果')),
                ('desc', models.CharField(max_length=100, verbose_name='备注')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '关闭'), (1, '开启')], default=1, verbose_name='状态')),
                ('deploy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_user', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_project', to='host_management.ProjectInfo', verbose_name='项目')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_url', to='host_management.DomainNameResolveInfo', verbose_name='域名')),
            ],
            options={
                'verbose_name': '上线表',
                'verbose_name_plural': '上线表',
            },
        ),
        migrations.CreateModel(
            name='TroubleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='平台名称')),
                ('event', models.CharField(max_length=50, verbose_name='事件')),
                ('event_time', models.DateField(verbose_name='故障时间')),
                ('handle_way', models.CharField(max_length=100, verbose_name='处理办法')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('handle_result', models.PositiveSmallIntegerField(choices=[(1, '已处理'), (2, '未处理'), (3, '暂时无法处理')], default=1, verbose_name='处理结果')),
                ('desc', models.CharField(max_length=100, verbose_name='备注')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '关闭'), (1, '开启')], default=1, verbose_name='状态')),
                ('handle_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_user', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_project', to='host_management.ProjectInfo', verbose_name='项目')),
            ],
            options={
                'verbose_name': '故障表',
                'verbose_name_plural': '故障表',
            },
        ),
        migrations.CreateModel(
            name='TroubleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
        ),
        migrations.AddField(
            model_name='troublerecord',
            name='tags',
            field=models.ManyToManyField(to='online_management.TroubleTag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='troublerecord',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_url', to='host_management.DomainNameResolveInfo', verbose_name='域名'),
        ),
    ]
