# Generated by Django 2.0.6 on 2018-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_management', '0004_auto_20180727_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troublerecord',
            name='event',
            field=models.CharField(max_length=50, verbose_name='事件和原因'),
        ),
        migrations.AlterField(
            model_name='troublerecord',
            name='handle_result',
            field=models.PositiveSmallIntegerField(choices=[(1, '已处理'), (2, '未处理'), (3, '其它')], default=1, verbose_name='处理结果'),
        ),
    ]
