# Generated by Django 2.0.6 on 2018-07-31 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_management', '0007_auto_20180728_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='事件名称')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '关闭'), (1, '开启')], default=1, verbose_name='状态')),
                ('op_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '运维事件表',
                'verbose_name_plural': '运维事件表',
            },
        ),
    ]
