# Generated by Django 2.0.6 on 2018-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_management', '0008_opsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsevent',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='opsevent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
