# Generated by Django 2.0.6 on 2018-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_management', '0009_auto_20180731_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsevent',
            name='start_time',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
    ]
