# Generated by Django 2.0.6 on 2018-07-05 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManageUserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opration', models.PositiveSmallIntegerField(choices=[(1, '添加'), (2, '修改'), (3, '停用')], verbose_name='操作')),
                ('op_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('ma_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ma_user', to=settings.AUTH_USER_MODEL, verbose_name='被操作用户')),
                ('op_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_user', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
        ),
    ]
