# Generated by Django 2.0.6 on 2018-07-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180706_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanageuserrecord',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(1, '添加'), (2, '修改'), (3, '启用'), (4, '停用')], verbose_name='操作'),
        ),
    ]
