# Generated by Django 2.0.6 on 2018-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180706_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogininfo',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, '登录'), (2, '登出')], default=1, verbose_name='动作'),
        ),
    ]
