# Generated by Django 2.0.6 on 2018-07-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180717_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanageuserrecord',
            name='ma_user',
        ),
        migrations.RemoveField(
            model_name='usermanageuserrecord',
            name='op_user',
        ),
        migrations.DeleteModel(
            name='UserManageUserRecord',
        ),
    ]
