# Generated by Django 2.0.6 on 2018-07-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_record', '0002_auto_20180725_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperationrecord',
            name='op_num',
            field=models.IntegerField(default=1, verbose_name='被操作项目ID'),
        ),
    ]
