# Generated by Django 2.0.6 on 2018-07-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_record', '0003_useroperationrecord_op_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroperationrecord',
            name='op_num',
            field=models.IntegerField(verbose_name='被操作项目ID'),
        ),
    ]
