# Generated by Django 2.0.6 on 2018-07-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0003_auto_20180726_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttags',
            options={'verbose_name': '分类表', 'verbose_name_plural': '分类表'},
        ),
    ]
