# Generated by Django 2.0.6 on 2018-07-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsysteminfo',
            name='bit',
            field=models.PositiveSmallIntegerField(choices=[(32, '32位'), (64, '64位')], default=64, verbose_name='位数'),
        ),
    ]
