# Generated by Django 2.0.6 on 2018-07-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0003_auto_20180709_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='idcinfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='operatingenvironmentinfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='operatingsysteminfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='useinfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], verbose_name='状态'),
        ),
    ]
