# Generated by Django 2.0.6 on 2018-07-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0005_auto_20180710_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态'),
        ),
    ]
