# Generated by Django 2.0.6 on 2018-07-10 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host_management', '0006_auto_20180710_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='服务名称')),
                ('version', models.CharField(max_length=20, verbose_name='服务版本')),
                ('listen_user', models.CharField(max_length=20, verbose_name='监听用户')),
                ('listen_port', models.CharField(max_length=30, verbose_name='监听端口')),
                ('ins_path', models.CharField(max_length=100, verbose_name='安装路径')),
                ('log_path', models.CharField(max_length=100, verbose_name='日志路径')),
                ('backup_path', models.CharField(max_length=100, verbose_name='备份路径')),
                ('start_cmd', models.CharField(max_length=100, verbose_name='启动命令')),
                ('desc', models.CharField(max_length=200, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], verbose_name='状态')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_management.HostInfo', verbose_name='主机')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '主机服务信息',
                'verbose_name_plural': '主机服务信息',
            },
        ),
    ]
