# Generated by Django 2.0.6 on 2018-07-12 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host_management', '0007_hostserviceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDBInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=20, verbose_name='用途')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_db_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
            ],
            options={
                'verbose_name': '数据库库表',
                'verbose_name_plural': '数据库库表',
            },
        ),
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=20, verbose_name='数据库名称')),
                ('db_version', models.CharField(max_length=20, verbose_name='数据库版本')),
                ('db_admin_user', models.CharField(max_length=20, verbose_name='数据库管理员')),
                ('db_admin_pass', models.CharField(max_length=20, verbose_name='数据库管理员密码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_host', to='host_management.UseInfo', verbose_name='主机')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '数据库信息',
                'verbose_name_plural': '数据库信息',
            },
        ),
        migrations.CreateModel(
            name='DatabaseUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_db', to='host_management.DatabaseInfo', verbose_name='数据库')),
                ('grant_db', models.ManyToManyField(to='host_management.DatabaseDBInfo', verbose_name='授权库')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '数据库用户表',
                'verbose_name_plural': '数据库用户表',
            },
        ),
        migrations.AlterField(
            model_name='hostserviceinfo',
            name='backup_path',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备份路径'),
        ),
        migrations.AlterField(
            model_name='hostserviceinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='databasedbinfo',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_db_db', to='host_management.DatabaseInfo', verbose_name='数据库'),
        ),
        migrations.AddField(
            model_name='databasedbinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_db_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
