# Generated by Django 2.0.6 on 2018-07-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0008_auto_20180712_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_host', to='host_management.HostInfo', verbose_name='主机'),
        ),
    ]
