# Generated by Django 2.0.6 on 2018-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0009_auto_20180712_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasedbinfo',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='库名'),
        ),
    ]
