# Generated by Django 2.0.6 on 2018-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0010_databasedbinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasedbinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='库名'),
        ),
    ]
