# Generated by Django 2.0.6 on 2018-07-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0011_auto_20180712_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuserinfo',
            name='grant_login',
            field=models.CharField(default='localhost', max_length=50, verbose_name='授权登录'),
        ),
    ]
