# Generated by Django 2.0.6 on 2018-07-13 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host_management', '0013_userhostoperationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainNameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dom_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dom_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '域名表',
                'verbose_name_plural': '域名表',
            },
        ),
        migrations.CreateModel(
            name='DomainNameResolveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dom_res_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_management.DomainNameInfo', verbose_name='域名')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dom_res_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '域名解析表',
                'verbose_name_plural': '域名解析表',
            },
        ),
        migrations.CreateModel(
            name='NetworkDviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='设备分类')),
                ('name', models.CharField(max_length=20, verbose_name='设备型号')),
                ('address', models.CharField(max_length=20, verbose_name='设备地址')),
                ('ip_in', models.GenericIPAddressField(verbose_name='内网 IP')),
                ('ip_out', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网 IP')),
                ('admin_user', models.CharField(max_length=20, verbose_name='管理用户')),
                ('admin_pass', models.CharField(max_length=20, verbose_name='管理密码')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '网络设备表',
                'verbose_name_plural': '网络设备表',
            },
        ),
        migrations.CreateModel(
            name='PortToPortInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_out', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网 IP')),
                ('port_out', models.IntegerField(verbose_name='外网端口')),
                ('ip_in', models.GenericIPAddressField(verbose_name='内网 IP')),
                ('port_in', models.IntegerField(verbose_name='内网端口')),
                ('use', models.CharField(max_length=20, verbose_name='用途')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '端口映射表',
                'verbose_name_plural': '端口映射表',
            },
        ),
    ]
