# Generated by Django 2.0.6 on 2018-07-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0014_domainnameinfo_domainnameresolveinfo_networkdviceinfo_porttoportinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainnameresolveinfo',
            name='name',
            field=models.CharField(default='www', max_length=20, verbose_name='二级域名'),
        ),
    ]
