# Generated by Django 2.0.6 on 2018-07-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0016_auto_20180715_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhostoperationrecord',
            name='op_user',
        ),
        migrations.DeleteModel(
            name='UserHostOperationRecord',
        ),
    ]
