# Generated by Django 2.0.6 on 2018-08-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0017_auto_20180724_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='cpu',
            field=models.CharField(max_length=50, verbose_name='CPU'),
        ),
    ]
