# Generated by Django 2.0.6 on 2018-08-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0018_auto_20180801_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='admin_pass',
            field=models.CharField(max_length=30, verbose_name='管理员密码'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='normal_pass',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='普通用户密码'),
        ),
    ]
