# Generated by Django 2.0.6 on 2018-08-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0019_auto_20180801_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='db_admin_pass',
            field=models.CharField(max_length=50, verbose_name='数据库管理员密码'),
        ),
        migrations.AlterField(
            model_name='databaseuserinfo',
            name='password',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='admin_pass',
            field=models.CharField(max_length=50, verbose_name='管理员密码'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='normal_pass',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='普通用户密码'),
        ),
        migrations.AlterField(
            model_name='networkdviceinfo',
            name='admin_pass',
            field=models.CharField(max_length=50, verbose_name='管理密码'),
        ),
    ]
