# Generated by Django 2.0.6 on 2018-07-18 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_type', models.PositiveSmallIntegerField(choices=[(1, '系统消息'), (2, '私信'), (3, '群发')])),
                ('subject', models.CharField(default='无标题', max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('rec_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms_send_user', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
        ),
    ]
