# Generated by Django 2.0.6 on 2018-07-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageinfo',
            options={'verbose_name': '消息表', 'verbose_name_plural': '消息表'},
        ),
    ]
