# Generated by Django 2.0.6 on 2018-07-18 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_auto_20180718_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReplayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msrep_message', to='message.MessageInfo', verbose_name='消息')),
                ('replay_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msrep_send_user', to=settings.AUTH_USER_MODEL, verbose_name='回复者')),
            ],
            options={
                'verbose_name': '回复消息表',
                'verbose_name_plural': '回复消息表',
            },
        ),
    ]
