# Generated by Django 2.0.6 on 2018-07-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_messageuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
