# Generated by Django 2.0.6 on 2018-07-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_messageinfo_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageuserinfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '保留'), (2, '删除'), (3, '永久删除')], default=1),
        ),
    ]
