# Generated by Django 2.0.6 on 2018-07-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20180718_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageinfo',
            name='rec_user',
        ),
    ]
