# Generated by Django 2.0.6 on 2018-08-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0002_auto_20180803_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforminfo',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='logo'),
        ),
    ]
