# Generated by Django 2.0.6 on 2018-08-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0003_auto_20180803_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuserinfo',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='平台密码'),
        ),
    ]
